/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nsigraph;

/**
 *
 * @author Lucas
 */
public class ViewGeneratorSelector extends javax.swing.JDialog {

    public ViewGenerator generator = new CircleGraphView();
    
    /**
     * Creates new form ViewGeneratorSelector
     */
    public ViewGeneratorSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void display(){
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_view = new javax.swing.JComboBox();
        btn_selectView = new javax.swing.JButton();

        setLocationByPlatform(true);
        setModal(true);
        setUndecorated(true);

        cb_view.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Circle View", "Random View", "Grid View" }));

        btn_selectView.setText("Ok");
        btn_selectView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_view, 0, 108, Short.MAX_VALUE)
                    .addComponent(btn_selectView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_selectView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectViewActionPerformed
        String val = (String)cb_view.getSelectedItem();
        switch(val){
            case "Circle View":
                generator = new CircleGraphView();
                break;
            case "Random View":
                generator = new RandomGraphView();
                break;
            case "Grid View":
                generator = new GridGraphView();
                break;
        }
        setVisible(false);
    }//GEN-LAST:event_btn_selectViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selectView;
    private javax.swing.JComboBox cb_view;
    // End of variables declaration//GEN-END:variables
}
